---
all:
  children:
    proxmox:
      hosts:
        pve_node:
          ansible_connection: local 
          ansible_host: 10.17.73.2
          
    proxy:
      hosts:
        npm_node:
          ansible_host: 192.168.10.101
          ansible_user: root

    # Group: All
    all_servers:
      children:
        proxy:
