---
all:
  children:
    proxmox:
      hosts:
        pve_node:
          ansible_connection: local 
          ansible_host: 10.17.73.2
          
    proxy:
      hosts:
        npm_node:
          ansible_host: 192.168.10.101
          ansible_user: root

    guacamole:
      hosts:
        guac_node:
          ansible_host: 192.168.10.100
          ansible_user: root

    dashboard:
      hosts:
        dash_node:
          ansible_host: 192.168.10.102
          ansible_user: root

    vmparty:
      hosts:
        vmparty_node:
          ansible_host: 192.168.10.103
          ansible_user: root

    all_servers:
      children:
        proxy:
        guacamole:
        dashboard:
        vmparty:

    vm_manager:
      children:
        guacamole:
        vmparty:
                
