---
- name: Enable IP Forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: true

- name: Configure Wi-Fi NAT/Masquerading 
  ansible.builtin.iptables:
    table: nat
    chain: POSTROUTING
    out_interface: "{{ wifi_interface }}"
    source: "{{ lxc_subnet }}"
    jump: MASQUERADE

- name: Rediriger les ports vers le LXC Nginx
  ansible.builtin.iptables:
    table: nat
    chain: PREROUTING
    in_interface: "{{ wifi_interface }}"
    destination: "{{ proxmox_ip }}"
    protocol: tcp
    destination_port: "{{ item.port_ext | int }}"
    jump: DNAT
    to_destination: "{{ npm_lxc_ip }}:{{ item.port_int }}"
  loop:
    - { port_ext: 80,   port_int: 80 }
    - { port_ext: 443,  port_int: 443 }
    - { port_ext: 8181, port_int: 81 }

- name: Save iptables rules
  ansible.builtin.shell:
    cmd: netfilter-persistent save
  changed_when: false