---
- name: Proxmox Configuration
  hosts: proxmox
  become: true
  roles:
    - proxmox

- name: Deploy Nginx Proxy Manager
  hosts: proxy
  become: true
  roles:
    - docker
    - nginxPM

- name: Deploy Guacamole Server
  hosts: guacamole
  become: true
  roles:
    - docker
    - guacamole

- name: Deploy Homepage (Dashboard)
  hosts: homepage
  become: true
  roles:
    - docker
    - homepage
