* Introduction

Documentation d'installation et de configuration du serveur.

* Installation

This section covers the different steps to automatically deploy the proxmox server. We used terraform and ansible to automate the deploiement

** Prerequisites
*** Proxmox VE

You need to install Proxmox VE on your server with a bootable key for example. You can follow this link: https://blog.stephane-robert.info/docs/virtualiser/type1/proxmox/fondamentaux/installation/.

*** Ansible

You need to install ansible on your server. One way to do is to use the pipx command.

**** Install pipx

#+begin_src bash
apt update && apt install -y pipx
#+end_src

**** Configure the path

#+begin_src bash
pipx ensurepath
#+end_src

**** Reload bash environment

#+begin_src bash
source ~/.bashrc
#+end_src

**** Install Ansible with pipx

#+begin_src bash
pipx install --include-deps ansible
#+end_src

The =--include-deps= argument is needed to use any ansible derivated command (eg. ansible-playbook, ...)

*** Terraform (or OpenTofu)

You need to install terraform on your server and configure it.

**** Installation

Follow this link to install terraform on your server: [[https://developer.hashicorp.com/terraform/tutorials/aws-get-started/install-cli][Terraform Install CLI]]

**** Configuration

We need to configure a terraform user with limited roles (security) to deploy our containers.

***** Create proxmox terraform role

#+begin_src bash
pveum role add TerraformProvider -privs "VM.Allocate VM.Audit VM.Clone VM.Config.Disk VM.Config.CPU VM.Config.Memory VM.Config.Network VM.Config.Options VM.Config.Cloudinit VM.Config.CDROM VM.Config.HWType VM.PowerMgmt VM.Console VM.Migrate VM.GuestAgent.Audit Datastore.Allocate Datastore.AllocateSpace Datastore.Audit Pool.Allocate Sys.Audit Sys.Modify SDN.Use"
#+end_src

***** Create terraform user

#+begin_src bash
  pveum user add terraform-user@pve
  pveum aclmod / -user terraform-user@pve -role TerraformProvider
#+end_src

***** Create an API token for your terraform user

#+begin_src bash
pveum user token add terraform-user@pve terraform-token -expire 0 -privsep 0 -comment "Terraform token"
#+end_src

Write the secret, it will never be displayed again!

***** Create a provider ssh key

This token will allow terraform and ansible to connect to the containers or vms via ssh to create and configure them.

#+begin_src bash
ssh-keygen -t ed25519 -C "proxmox-provider" -f ~/.ssh/id_ed25519_terraform -N ""
#+end_src

** Proxmox Configuration

There is an ansible role to configurate proxmox for next steps. It will install packages and configure wifi network.

From the ansible folder, run this script to install system tools:

#+begin_src bash
ansible-playbooks playbooks/site.yml --limit proxmox
#+end_src

** WiFi Configuration
*** Information

|---------+-------------------|
| Name    | REDACTED   |
| REDACTED    | REDACTED |
|---------+-------------------|

Ressource: https://github.com/ThomasRives/Proxmox-over-wifi/blob/main/README.md

*** Prerequisites
**** Detect USB dongle

To verify if the dongle is recognized by the server.

#+begin_src bash
lsusb
#+end_src

Search for device with wifi driver name (eg. 88xbu)

*** Interface

In =/etc/network/interfaces=, copy & paste this text. The wpa_supplicant.conf file describes the interface connection. You can crypt your password (in next modules).

#+begin_src 
allow-hotplug REDACTED
iface REDACTED inet dhcp
        dns-nameservers 1.1.1.1 8.8.8.8
        wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf
#+end_src

*** Credentials

You can add a network in =/etc/wpa_supplicant/wpa_supplicant.conf= file.

**** IONIS configuration

#+begin_src
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1

network={
  ssid="IONIS"
  scan_ssid=1
  eap=PEAP
  key_mgmt=WPA-EAP

  phase2="auth=MSCHAPV2"

  identity="<mail>@epitech.eu"
  password=hash:<your_hashed_password>

  phase1="peapver=0"
}
#+end_src

*** Crypt WiFi Password

This command will crypt your password to enhance security.

#+begin_src sh
  echo -n "<your_password>" | iconv -t utf16le | openssl dgst -provider legacy -provider default -md4
#+end_src

*** Pass Internet to your VMs and Containers.

With WiFi, simple bridge doesn't work (device block multiple mac adresses resolution). You will need to use NAT/Masquering method.

**** Virtual Bridge

Example: <vm_gateway_address> = 192.168.10.1; <vm_network> = 192.168.10.0; <vm_network_mask> = 24

#+begin_src 
auto vmbr0
iface vmbr0 inet static
        address <vm_gateway_address>/<vm_network_mask>
        bridge-ports none
        bridge-stp off
        bridge-fd 0

        post-up echo 1 > /proc/sys/net/ipv4/ip_forward
        post-up iptables -t nat -A POSTROUTING -s '<vm_network>/24' -o REDACTED -j MASQUERADE
        post-down iptables -t nat -D POSTROUTING -s '<vm_network>/24' -o REDACTED -j MASQUERADE
#+end_src

**** Dnsmasq
***** Installation

#+begin_src bash
sudo apt install dnsmasq
#+end_src

***** Configuration

Ensure these lines are active:

#+begin_src 
# Listen on the vmbr0 bridge
interface=vmbr0
# Disable default DHCP on other interfaces
except-interface=lo
except-interface=[wifi_interface]
# Do this for every unused interface
except-interface=[other_unused_interface]

# DHCP Range for VMs
dhcp-range=[first_ip_of_VM_in_vm_network],[last_ip_of_VM_in_vm_network],[netmask_in_dot_format_for_VM_network],[lease_time]
# Example:
# dhcp-range=10.10.1.194,10.10.1.222,255.255.255.224,24h

# Gateway and DNS for VMs (points to the Proxmox host)
dhcp-option=3,[Proxmox_host_IP]
dhcp-option=6,[Proxmox_host_IP]

conf-dir=/etc/dnsmasq.d,*.conf
#+end_src

****** Static IP

Static IPs for VMs are setted with Terraform, not in the dnsmasq configuration file.

***** Restart

#+begin_src bash
  sudo systemctl restart dsnmasq
#+end_src

** Nginx Proxy Manager

We use a local Nginx Proxy Manager to map urls to ip:port. For example, a student taps "my_server.domainepitech" url in his browser and it redirects to "192.168.1.1:4000" internally without showing him.

*** Deploy

The Nginx PM container is defined in =terraform/nginxPM.tf= file.

#+begin_src bash
terraform apply -target="proxmox_virtual_environment_container.nginxpm"
#+end_src

*** Configurate

To configurate run this ansible command.

#+begin_src bash
ansible-playbook playbooks/site.yml --limit nginxpm
#+end_src

** Guacamole

Guacamole server is used to facilitate student connection to a vm. It also supports rdp protocol. It uses the microsoft students credentials (microsoft entra id)

*** Deploy

#+begin_src bash
terraform apply -target="proxmox_virtual_environment_container.guacamole"
#+end_src

*** Configurate

#+begin_src bash
ansible-playbook playbooks/site.yml --ask-vault-pass --limit guacamole  
#+end_src

You will need to add vault pass to configure guacamole for database user credentials.

** HUB Workshop Web App (Student project) [Work In Progress]

** Intranet [Work In Progress]

** GiTea [Work In Progress]

* Todos
* Version
* Public Deployement solution
** Solution 1

VPS (install WireGuard server (reverse tunneling) & Nginx (reverse proxy))
Proxmox (install WireGuard client)

Problème: Impossible d'avoir une IP publique accessible partout avec IONIS sans demander autorisation à Epitech avec potentiellement un refus.
Principe: Etudiant utilise l'adresse publique du vps qui redirige (via un VPN (tunnel entre vps et promox) + Nginx (traduit ip publique vers ip de l'interface proxmox)) vers proxmox.

Problèmes: VPS de Google donc les données transitent par eux.
VPS coûte de l'argent (le mien est gratuit pendant quelques mois).

Ajout nom de domaine gratuit (duckdns)
On pourrait ajouter un nom de domaine pour avoir plusieurs redirection sans ouvrir de port (config via Nginx).

** Solution 2

On demande à Epitech d'avoir des sous-domaines de epitech.eu (sous-domaine wildcard) pour permettre la redirection des liens mais configuration de leur part de leur reverse proxy (plus ou moins complexe d'ajouter un site).

** Solution 3 (local)

Disponible que sur IONIS, les étudiants doivent être sur le réseau de l'école pour avoir accès.
Nom de domaine (soit epitech officiel soit autre temporairement) + Ajouter Nginx en local sur le serveur pour les redirections.

